### ISSUE TITLE
R package doesn't begin with r-

### ISSUE THREAD

**Issue by mingwandroid** [conda-forge/xtensor-r-feedstock#2]
Can we call this r-xtensor-r? We have done some work about ecosystem namespaces and this will prevent that from working correctly.

It will also break my tooling.

Cc @kalefranz, @msarahan

**Comment by bgruening** [comment]
Yes, it does not depend on r-base, its just a strange name :)

**Comment by SylvainCorlay** [comment]
- xtensor-r is a header-only c++ library for the general prefix.
- the headers of xtensor-r include those of r and rcpp.

**Comment by SylvainCorlay** [comment]
> Ah ok sorry I didn't do my homework here!

Thanks for checking!

Regarding R packaging, I am looking at the best way to set up the actual R package for CRAN, conda-forge, while being installable with devtools from github.

At the moment, the CRAN package tarball is built from a special cmake target, and vendors `xtl`, `xtensor` and `xtensor-r` headers, but this makes it unsuitable to devtools github installation (since xtl, xtensor and xtensor-r are not included in the repository obviously).

Is there a sort of free form script that would be executed when doing a devtool installation? This would allow me to have the github installation without including dependencies in the github repo, and to disable the vendoring when I package it for conda-forge or other general-purpose package managers.

**Comment by mingwandroid** [comment]
Can you use git submodules here perhaps? I'm not too familiar with devtools.

**Comment by mingwandroid** [comment]
On this lib naming issue, a (maybe, maybe not) interesting bit of history from the GNU world:

`libiberty` (an internal library used by many GNU projects that's now largely deprecated by gnulib) is so named so that when you link to it, you pass the flag `-liberty`.
